#!/bin/sh

# lcov --capture --directory test-build/ \
#     --output-file coverage.info \
#     --exclude '*test_*' \
#     --exclude '*cmd.c*' \
#     --exclude '*server.c*' \
#     --exclude '*utils*'

lcov --capture --directory test-build/ \
    --output-file coverage.info

lcov --summary coverage.info
# genhtml coverage.info --output-directory coverage

lcov --extract coverage.info "*logwrap.c" --output-file source_file.info \
    | grep "lines" | awk '{print $2}' | sed 's/%//'
