name: Build & Tests
run-name: Running build & tests for push by ${{ github.actor }}
on: [push]

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      # Tests
      - run: make
      - run: test/run_tests
      # Coverage
      - uses: hrishikesh-kadam/setup-lcov@v1
      - run: test/coverage | tee cov
      - name: Put coverage into an environment variable
        run: echo "COVERAGE=$(cat cov | tail -n1)" >> $GITHUB_ENV
      - name: Print coverage
        run: cat cov | tail -n1
      - name: Build-A-Badge
        uses: peterrhodesdev/build-a-badge@v1.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: coverage
          label: Coverage
          color: green
          message: ${{ env.COVERAGE }}%
