name: Build & Tests
run-name: Running build & tests for push by ${{ github.actor }}
on: [push]

jobs:
  run-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make

  run-tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: run-build
    steps:
      - uses: actions/cache@v4
      - run: make test
